# Generated by Django 4.2 on 2023-04-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperIndex',
            fields=[
                ('serial_no', models.IntegerField(default=0)),
                ('journal_name', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('scopus', models.CharField(max_length=100, null=True)),
                ('wos', models.CharField(max_length=100, null=True)),
                ('abdc', models.CharField(max_length=100, null=True)),
                ('abs', models.CharField(max_length=100, null=True)),
                ('ft50', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
